/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FuncionarioController;
import dao.FuncionarioDao;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FuncionarioModel;

/**
 *
 * @author Kito Mahique
 */
public class ListagemFuncionario extends javax.swing.JFrame {

    int nivel=2;

    public int getNivel() {
        return nivel;
    }

    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    
    
    public ListagemFuncionario() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.DARK_GRAY);
        jbProcurar.setBackground(Color.white);
        jbRefrescarTabela.setBackground(Color.white);
        jbVoltar.setBackground(Color.white);
        jbEliminar.setBackground(Color.white);
        jbActualizar.setBackground(Color.white);
        preenchertabela();
        
    }
    
    public void preenchertabela(){
        DefaultTableModel tabela = (DefaultTableModel)jtTabela.getModel();
        FuncionarioDao d = new FuncionarioDao();
        List<FuncionarioModel> lista;
        lista = d.listar();
        for(int i=0; i<lista.size(); i++){
            Object[] dados = {lista.get(i).getId(), lista.get(i).getNomeCompleto(), lista.get(i).getNumeroBi(), 
                lista.get(i).getGenero(), lista.get(i).getDataDeNascimento(),
                lista.get(i).getNacionalidade(), lista.get(i).getLocalResidencia(), 
            lista.get(i).getEstadoCivil(), lista.get(i).getCategoria(), lista.get(i).getSenha(), 
            lista.get(i).getContacto(), lista.get(i).getEmail()};
            tabela.addRow(dados);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbEliminar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jtProcurar = new javax.swing.JTextField();
        jbProcurar = new javax.swing.JButton();
        jlProcura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jbRefrescarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jbEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1814090_delete_garbage_trash_icon.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/103514_edit_text_document_icon.png"))); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2303135_arrow_back_left_refresh_renew_icon.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtProcurar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtProcurar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbProcurar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2303114_explore_lense_magnifier_search_searching_icon.png"))); // NOI18N
        jbProcurar.setText("Procurar");
        jbProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcurarActionPerformed(evt);
            }
        });

        jlProcura.setBackground(new java.awt.Color(255, 255, 255));
        jlProcura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlProcura.setForeground(new java.awt.Color(255, 255, 255));
        jlProcura.setText("Nome");

        jtTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "BI", "GENERO", "DT  NASCIMETNTO", "NACIONALIDADE", "RESIDENCIA", "ESTADO CIVIL", "CATEGORIA", "SENHA", "CONTACTO", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTabela.setRowHeight(40);
        jtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        jbRefrescarTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbRefrescarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11116_refresh_icon.png"))); // NOI18N
        jbRefrescarTabela.setText("Refrescar Tabela");
        jbRefrescarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefrescarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlProcura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1128, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jbProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRefrescarTabela)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jlProcura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRefrescarTabela))
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcurarActionPerformed
        String procura = jtProcurar.getText();
        DefaultTableModel tabela = (DefaultTableModel)jtTabela.getModel();
        
        FuncionarioDao dp = new FuncionarioDao();
        List<FuncionarioModel> listap;
        
        listap = dp.listar();
        for(int i=0; i<listap.size(); i++){
            if(listap.get(i).getNomeCompleto().equalsIgnoreCase(procura)){
                tabela.setRowCount(0);
                Object[] dados = {listap.get(i).getId(), listap.get(i).getNomeCompleto(), listap.get(i).getNumeroBi(), 
                listap.get(i).getGenero(), listap.get(i).getDataDeNascimento(),
                listap.get(i).getNacionalidade(), listap.get(i).getLocalResidencia(), 
                listap.get(i).getEstadoCivil(), listap.get(i).getCategoria(), listap.get(i).getSenha(), 
                listap.get(i).getContacto(), listap.get(i).getEmail()};
                tabela.addRow(dados);
            }
        }
                
    }//GEN-LAST:event_jbProcurarActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        if(getNivel() == 1){
            new Menu().setVisible(rootPaneCheckingEnabled);
            this.dispose();
        }else{
            new MenuFuncionario().setVisible(rootPaneCheckingEnabled);
            this.dispose();
        }
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
       int indiceLinha = jtTabela.getSelectedRow();
       if(indiceLinha!=-1){
        int a= JOptionPane.showConfirmDialog(null, "POR FAVOR CONFIRME A ACTUALIZACAO", "Actualizar", JOptionPane.YES_NO_OPTION);
          if(a==JOptionPane.YES_OPTION){
            FuncionarioController fA = new FuncionarioController();
              
            fA.actualizar(jtTabela.getValueAt(indiceLinha, 0).toString(), 
       jtTabela.getValueAt(indiceLinha, 1).toString(), 
       jtTabela.getValueAt(indiceLinha, 2).toString(), 
       jtTabela.getValueAt(indiceLinha, 3).toString(), 
       jtTabela.getValueAt(indiceLinha, 4).toString(), 
       jtTabela.getValueAt(indiceLinha, 5).toString(), 
       jtTabela.getValueAt(indiceLinha, 6).toString(), 
       jtTabela.getValueAt(indiceLinha, 7).toString(), 
       jtTabela.getValueAt(indiceLinha, 8).toString(), 
       jtTabela.getValueAt(indiceLinha, 9).toString(), 
       jtTabela.getValueAt(indiceLinha, 10).toString(), 
       jtTabela.getValueAt(indiceLinha, 11).toString());
            
            DefaultTableModel tabela = (DefaultTableModel)jtTabela.getModel();
        tabela.setRowCount(0);
        preenchertabela();
              
          }
        
       }
       
       
        
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaMouseClicked
    }//GEN-LAST:event_jtTabelaMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
       int indiceLinha = jtTabela.getSelectedRow();
       if(indiceLinha!=-1){
//        
        int a= JOptionPane.showConfirmDialog(null, "DESEJA ELIMINAR? CONFIRME!", "ELIMINAR", JOptionPane.YES_NO_OPTION);
          if(a==JOptionPane.YES_OPTION){
              int id = (int)(jtTabela.getValueAt(indiceLinha, 0));
             FuncionarioController fE = new FuncionarioController();
             
             fE.eliminar(id);
             
              
            DefaultTableModel tabela = (DefaultTableModel)jtTabela.getModel();
        tabela.setRowCount(0);
        preenchertabela();
          }
        
       }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbRefrescarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefrescarTabelaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel)jtTabela.getModel();
        tabela.setRowCount(0);
        preenchertabela();
    }//GEN-LAST:event_jbRefrescarTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ListagemFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbProcurar;
    private javax.swing.JButton jbRefrescarTabela;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlProcura;
    private javax.swing.JTextField jtProcurar;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables
}
