/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FuncionarioController;
import controller.ProcessoController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Kito Mahique
 */
public class MenuFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form MenuFuncionario
     */
    public MenuFuncionario() {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbListarProcesso = new javax.swing.JButton();
        jbEstatistica = new javax.swing.JButton();
        jlImagem = new javax.swing.JLabel();
        jbVisitas = new javax.swing.JButton();
        jbOcorrencias = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiTerminarSessao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiFecharPrograma = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 670));

        jbListarProcesso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbListarProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista-de-desejos.png"))); // NOI18N
        jbListarProcesso.setText("CONSULTAR PROCESSOS");
        jbListarProcesso.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jbListarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarProcessoActionPerformed(evt);
            }
        });

        jbEstatistica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEstatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estatisticas.png"))); // NOI18N
        jbEstatistica.setText("RELATORIO GERAL             ");
        jbEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstatisticaActionPerformed(evt);
            }
        });

        jlImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/n-removebg-preview.png"))); // NOI18N
        jlImagem.setPreferredSize(new java.awt.Dimension(541, 541));

        jbVisitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visitantes.png"))); // NOI18N
        jbVisitas.setText("      VISITAS                           ");
        jbVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisitasActionPerformed(evt);
            }
        });

        jbOcorrencias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbOcorrencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jbOcorrencias.setText("OCORRENCIAS                    ");
        jbOcorrencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOcorrenciasActionPerformed(evt);
            }
        });

        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 40));

        jMenu1.setText("OPCOES");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiTerminarSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/off.png"))); // NOI18N
        jmiTerminarSessao.setText("TERMINAR SESSAO");
        jmiTerminarSessao.setPreferredSize(new java.awt.Dimension(149, 30));
        jmiTerminarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTerminarSessaoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiTerminarSessao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("EXPLORAR");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/envolvimento-dos-funcionarios.png"))); // NOI18N
        jMenuItem1.setText("LISTAR FUNCIONARIOS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jmiFecharPrograma.setText("FECHAR");
        jmiFecharPrograma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel.png"))); // NOI18N
        jMenuItem2.setText("FECHAR PROGRAMA");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(161, 30));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmiFecharPrograma.add(jMenuItem2);

        jMenuBar1.add(jmiFecharPrograma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEstatistica, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbListarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(jlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbListarProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jbVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jbOcorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbEstatistica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jlImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbListarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarProcessoActionPerformed
        new ListagemProcesso();
        this.dispose();
    }//GEN-LAST:event_jbListarProcessoActionPerformed

    private void jmiTerminarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTerminarSessaoActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(null, "DESEJA TERMINAR SESSAO?", "SESSAO", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
            new TelaLogin();
            this.dispose();
        }

    }//GEN-LAST:event_jmiTerminarSessaoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(null, "DESEJA FECHAR PROGRAMA?", "FECHAR", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstatisticaActionPerformed
        ProcessoController p = new ProcessoController();
        p.relatorio(2);
        this.dispose();
    }//GEN-LAST:event_jbEstatisticaActionPerformed

    private void jbOcorrenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOcorrenciasActionPerformed
        // TODO add your handling code here:
      RegistoComportamental j = new RegistoComportamental();
      j.setVisible(true);
      j.setNivel(2);
        
    }//GEN-LAST:event_jbOcorrenciasActionPerformed

    private void jbVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisitasActionPerformed
        // TODO add your handling code here:
        Visitas v = new Visitas ();
         v.setVisible(true);
      v.setNivel(2);
        
        
    }//GEN-LAST:event_jbVisitasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FuncionarioController f = new FuncionarioController("listar", 2);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbEstatistica;
    private javax.swing.JButton jbListarProcesso;
    private javax.swing.JButton jbOcorrencias;
    private javax.swing.JButton jbVisitas;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JMenu jmiFecharPrograma;
    private javax.swing.JMenuItem jmiTerminarSessao;
    // End of variables declaration//GEN-END:variables
}
